### ISSUE TITLE
Getting XCode err - ld: library not found for -lAIBSQLite

### ISSUE THREAD

**Issue by winkler1** [almost/react-native-sqlite-example#1]
Total xcode noob here, probably missing something obvious?

**Comment by almost** [comment]
That's the xcode project name for the `react-native-sqlite` library. Some things to check:
1. First shut down xcode complete
2. Now make sure the dependencies are installed by running "npm install ." from a terminal in the project directory
3. Re-open xcode, check that "AIBSQLite" is showing as a sub-project and that you can expand it to the see the files inside. It should look like this:
   ![xcode](https://cloud.githubusercontent.com/assets/11125/7046445/b4109b9c-ddfd-11e4-883a-566e67925ade.png) 

If it's not showing as a sub-project, or if it's showing but it's not expandable, then try dragging in the project from `node_modules/react-native-sqlite/AIBSQLite.xcodeproj` onto the example project.

Let me know if you still have problems. XCode is full of these fun cryptic config issues!
