### ISSUE TITLE
Xcode: Library not found for -lAIBSQLite

### ISSUE THREAD

**Issue by chris-alexander55** [almost/react-native-sqlite-example#4]
I cloned the repo and ran npm install. When I open in Xcode, I get the following error. This has been a persistent error for me. Are you using Cocoapods or some other undocumented dependency? Thanks!

ld: library not found for -lAIBSQLite
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/SQLiteExample.app/SQLiteExample normal x86_64
    cd /Users/calexander/Projects/react-native-sqlite-example
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -L/Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator -F/Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator -filelist /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Intermediates/SQLiteExample.build/Debug-iphonesimulator/SQLiteExample.build/Objects-normal/x86_64/SQLiteExample.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=7.0 -lsqlite3 -lAIBSQLite -licucore /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libReact.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTWebSocketDebugger.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTAdSupport.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTImage.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTVibration.a /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/libRCTText.a -Xlinker -dependency_info -Xlinker /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Intermediates/SQLiteExample.build/Debug-iphonesimulator/SQLiteExample.build/Objects-normal/x86_64/SQLiteExample_dependency_info.dat -o /Users/calexander/Library/Developer/Xcode/DerivedData/SQLiteExample-fgqeuiwklukqetfztrrkoydxzwhc/Build/Products/Debug-iphonesimulator/SQLiteExample.app/SQLiteExample

**Comment by almost** [comment]
This sometimes happens,I think it might be because you openned it in xcode before you did the NPM install. Xcode can't find the depedency so removes it from the list, then even when you have installed it it won't find it again.

To fix it go to "Build Phases" in xcode then "Link binary with Libraries" then make sure you've added AIBSQLite. You should be able to add it by clicking the + and selecting from the list. If you don't see it on the list then you need to make sure the AIBSQLite project is showing up as a sub-project in xcode (see the react-native-sqlite readme)

**Comment by chrisalexander55** [comment]
Followed your directions, still fails when opening in Xcode with the above message. Note: 1. After performing $npm i, no node_modules exist in react-native-sqlite. Is this correct?  2. I can't believe others aren't experiencing this issue. Is anyone else using or trying to use this module who is not a contributor?

**Comment by almost** [comment]
I've heard from a few people who have been trying with this example. I'm still figuring out the best ways to set things up to minimise issues people have though, React Native is still pretty new and I'm sure best practices will emerge over time.

I've just upgraded it to use the latest `react-native-sqlite` which should did fix some path issues some people were having. Give it a try with the latest version (I'd recommend deleting your working directory and re-cloning just to make it simple)

**Comment by chris-alexander55** [comment]
Now there is an additional error:

RCTBridgeModule.h not found

I'm moving onto AsyncStorage after 3 weeks of posting issues here. Thanks for sharing this repo but hopefully a solution that wraps FMDB will emerge from the community.

**Comment by andyxhadji** [comment]
Any update on the RCTBridgeModule.h not found issue?

**Comment by andyxhadji** [comment]
Nevermind, solved the issue. I moved the AIBSQLite.xcodeproj out of the node_modules directory, before adding it to the project through x-code, causing some directory location issues.
